<a href="https://colab.research.google.com/github/VimalChamyal/Logistic-Regression/blob/main/Iris_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the commonly used libraries

In [61]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Loading the dataset from my github

In [62]:
url = 'https://raw.githubusercontent.com/VimalChamyal/Logistic-Regression/main/IRIS.csv'
df1 = pd.read_csv(url)

In [33]:
df1.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [34]:
df1['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [35]:
df1.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [36]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


Split the data

In [37]:
X = df1.drop('species', axis = 1)
X.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [38]:
y = df1['species']
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: species, dtype: object

In [39]:
X.shape

(150, 4)

In [40]:
y.shape

(150,)

Train Test Split

In [41]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [42]:
X_train.shape

(100, 4)

In [43]:
X_test.shape

(50, 4)

Scale the data

In [74]:
from sklearn.preprocessing import StandardScaler

In [75]:
scaler = StandardScaler()

Train the scaler

In [76]:
scaler.fit(X_train)

StandardScaler()

Perform scaling

In [77]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [78]:
X_test

array([[ 0.34288234, -0.497631  ,  0.51155872, -0.02416432],
       [-0.13835603,  1.91805346, -1.22646639, -1.2323802 ],
       [ 2.26783585, -0.98076789,  1.78611047,  1.45254398],
       [ 0.22257275, -0.25606255,  0.39569038,  0.37857431],
       [ 1.1850495 , -0.497631  ,  0.56949289,  0.2443281 ],
       [-0.49928482,  0.95177968, -1.34233473, -1.09813399],
       [-0.25866563, -0.25606255, -0.12571715,  0.11008189],
       [ 1.30535909,  0.22707434,  0.7432954 ,  1.45254398],
       [ 0.46319194, -1.94704167,  0.39569038,  0.37857431],
       [-0.01804644, -0.73919944,  0.04808536, -0.02416432],
       [ 0.82412072,  0.46864278,  0.7432954 ,  1.04980535],
       [-1.22114238, -0.01449411, -1.4002689 , -1.50087261],
       [-0.37897522,  1.19334812, -1.45820307, -1.36662641],
       [-1.10083279,  0.22707434, -1.34233473, -1.50087261],
       [-0.8602136 ,  1.91805346, -1.34233473, -1.2323802 ],
       [ 0.58350153,  0.71021123,  0.51155872,  0.51282052],
       [ 0.82412072, -0.

Model Building

In [79]:
from sklearn.linear_model import LogisticRegression

In [80]:
model = LogisticRegression()

In [81]:
model.fit(X_train, y_train)

LogisticRegression()

Predict

In [82]:
prediction = model.predict(X_test)

In [83]:
prediction

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica'], dtype=object)

In [84]:
np_y_test = np.array(y_test)

In [85]:
np_y_test

array(['Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica'], dtype=object)

Evaluation

In [86]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [87]:
print(classification_report(y_test, prediction))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       0.94      1.00      0.97        15
 Iris-virginica       1.00      0.94      0.97        16

       accuracy                           0.98        50
      macro avg       0.98      0.98      0.98        50
   weighted avg       0.98      0.98      0.98        50



In [88]:
accuracy_score(y_test, prediction)

0.98

In [89]:
print(confusion_matrix(y_test, prediction))

[[19  0  0]
 [ 0 15  0]
 [ 0  1 15]]
